ueno/ruby-gpgme

ext/gpgme/extconf.rb
gpgme.gemspec

One of the major enhancements in mini_portile2 is to take `configure_options` literally without running in subshell, see: https://github.com/flavorjones/mini_portile/commit/e77b90938828980e670278e1c3bf83a62515a7fd.
The compatibility fix has been made at: https://github.com/ueno/ruby-gpgme/commit/661739705e7f63934e68f6b91115227fa309fb38. Unfortunately this breaks build with mini_portile < 0.7 (currently `>= 0.5.0` in gemspec) when `ENV['CFLAGS']` is present.
A gemspec dependency update seems to be necessary. But instead of depending any of the 0.7.0.rc* release, let's go straight into v2.

Switch to use mini_portile2 for building native libraries

---

gpgme.gemspec

Relax mini_portile2 version dependency, to prevent conflicts with nokogiri 1.8.0 (which requires mini_portile2 ~>2.2.0)
Fixes #88

Relax mini_portile2 version dependency

---

ext/gpgme/extconf.rb

Downloading files from FTP without checksum validation is insecure and opens a potential security hole in the system. Instead, we will download library sources via HTTPS and then validate file signatures locally. This will make sure files are not modified in flight, and also will make sure that if somebody managed to replace files on the server – we will fail fast and stop compiling the potentially malicious code.

Switch to HTTPS + checksum validation for GPG libraries

---

gpgme.gemspec

Currently nokogiri 1.6.x has a vulnerability and Updating to 1.8.x is blocked due to the mini_portile2 compatibility.
```
gpgme (~> 2.0) was resolved to 2.0.14, which depends on
mini_portile2 (~> 2.1)
nokogiri (= 1.8.1) was resolved to 1.8.1, which depends on
mini_portile2 (~> 2.3.0)
```

Nokogiri 1.8.1 compatibility update

---

ext/gpgme/gpgme_n.c
lib/gpgme/data.rb
test/data_test.rb

When using `gpg -dv <filename>` to decrypt a file, it displays **"original file name"** that shows the name of the original file before encrypting. But when encrypting from `GPGME::Data` stream, the file name was lost. And gpg displays "-&20" or similar string as the original file name.
This commit adds the ability to set the `file_name` property of `GPGME::Data` object, this property will be displayed as **"original file name"** when decrypting with `gpg -dv` command.
This solves #99

Expose gpgme_data_set_file_name

---

ext/gpgme/extconf.rb
test/crypto_test.rb

The motivation behind this PR is to use the latest versions of gpgme,
libassuan, and libgpg-error. This change will be useful to those
running ruby within Docker, where gpgme 1.9 has very poor performance
due to inefficiently attempting to close as many file descriptors as
`RLIMIT_NOFILE` allows on every spawn. This has been resolved in gpgme 1.12 by
checking directory entries in /proc/self/fd to determine how many file
descriptors to attempt to close.
Of note is that the error reporting has changed slightly, such that `NoSecretKey` is returned now instead of `DecryptFailed` in `crypto_test.rb`.

updates gpgme 1.12.0, assuan 2.5.1, error 1.32

---

ext/gpgme/extconf.rb

This disables more tests when building gpgme. This adds a significant amount of installation time and it also currently prevents this gem from being installed on MacOS.
On MacOS, it fails with a message like the following:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /Users/dirkjan/github/github/vendor/gems/2.5.2/ruby/2.5.0/gems/gpgme-2.0.17/ext/gpgme
/Users/dirkjan/github/github/vendor/ruby/784b3dda879bfe72f4416b516baa08608e22d571/bin/ruby -r
./siteconf20181122-46971-oal80.rb extconf.rb
************************************************************************
IMPORTANT!  gpgme gem uses locally built versions of required C libraries,
namely libgpg-error, libassuan, and gpgme.
If this is a concern for you and you want to use the system library …
```

Disable running tests when configuring gpgme

---

.travis.yml
test/crypto_test.rb
test/ctx_test.rb
test/key_test.rb
test/pinentry
test/sub_key_test.rb
test/test_helper.rb

This makes Travis builds succeed, though it still doesn't cover all the GnuPG versions (for >= 2.1, I guess  we should make use of `:pinentry_mode => PINENTRY_MODE_LOOPBACK` instead of the dummy pinentry program; I don't want to bother with this kind of stupidity).

Fix test failures on Travis CI

---

lib/gpgme/data.rb

Starting here, reading the `encoding=` docs:
https://www.rubydoc.info/github/ueno/ruby-gpgme/GPGME%2FData:encoding=
Was having trouble finding examples of how this method is used. Was thinking I could pass it strings like `"UTF-8"` or `"Windows-1252"` or `"ISO-8859-1"` but actually it takes integers 0 to 7 matching the `enum` in the underlying GPGME code. Hoping this would be helpful documentation.

More verbose comments derived from GPGME code

---

gpgme.gemspec

Gem specification attribute #has_rdoc is deprecated and ignored. According to deprecation warning, it may be removed "on or after 2018-12-01" with no replacement.
This attribute used to describe whether RDoc can be generated for given gem or not.  According to RubyGems v1.3.3 release notes, "RDoc is now generated regardless of Gem::Specification#has_rdoc?".
See:
- https://blog.rubygems.org/2009/05/04/1.3.3-released.html

Remove has_rdoc from gemspec

---

lib/gpgme/ctx.rb
lib/gpgme/key.rb
test/ctx_test.rb
test/key_test.rb
test/support/resources.rb

'Minimal' is the smallest possible key, all signatures removed except
for the latest self-signatures.
~~Note: I will have to fix the tests, can't run them locally due to <https://dev.gnupg.org/T4459>.~~

Enable minimal key exports.

---

lib/gpgme/ctx.rb

Hey there! Here's a bug fix for an issue that was causing file descriptors to double-close in our test suite.
Commit message inline:
```
The default callback for writing a password to GPGME takes a file
descriptor and needs to write the given password to it. By creating a
new `IO` object directly on the file descriptor, the object will take
ownership of it. This is a problem because the file descriptor passed to
this callback will be explicitly closed by GPGME, and eventually, the
`IO` allocated in `self.pass_function` will be garbage collected,
closing the file descriptor again.
Usually, closing a file descriptor that has already been closed results
in a silent `EBADFD`, but a serious race condition can happen if the
Kernel allocates the same file descriptor (e.g. through another `open` …
```

ctx: do not autoclose in `pass_function`

---

ext/gpgme/extconf.rb

fixes: https://github.com/ueno/ruby-gpgme/issues/149  
Also likely fixes the "issues with posix-io.c" from here: https://github.com/ueno/ruby-gpgme/issues/98#issuecomment-359652593
Main reason for my PR was having gpgme 1.13.1 fail to build its native ext due to the bug fixed in this ticket: https://dev.gnupg.org/T5587  
To whoever reviews this, thank you 🙂

bump gpgme to 1.17.0 for bugfixes

---

gpgme.gemspec

This PR makes the required version of `mini_portile2` less restrictive so it can be installed in projects that already have anything greater than `2.7` and less than version 3 of the `mini_portile2` gem  installed.

Set mini_portile2 required version to be less restrictive

---

ext/gpgme/extconf.rb

https://github.com/ueno/ruby-gpgme/pull/166 changed from `pkg-config` to `gpgme-config`, but if `PKG_CONFIG_PATH` is not set properly, the C extension library will quietly build without the right linker dependencies.
To fix this, we now check for the existence of `gpgme.pc` in `PKG_CONFIG_PATH` and attempt to fall back to `gpgme-config` if it does not exist.
Closes https://github.com/ueno/ruby-gpgme/issues/167

Improve checks for pkg-config and fall back to gpgme-config

---

.github/workflows/test.yml

The tests pass locally, what about adding it to CI pipeline to signify Ruby 3.2 support

Add Ruby 3.2 to CI pipeline

---

NEWS
ext/gpgme/gpgme_n.c
gpgme.gemspec
lib/gpgme/version.rb

Issues: 
- [Build failure with Clang 16 (-Wincompatible-function-pointer-types)](https://github.com/ueno/ruby-gpgme/issues/171)
- [gpgme_n.c: error: incompatible function pointer types passing VALUE](https://bugs.gentoo.org/881203)
Fix explanation: Update the method `rb_s_gpgme_op_keylist_ext_start` to have 1 more param `VALUE vreserved`
Ref: 
- https://wiki.gentoo.org/wiki/Modern_C_porting
- https://github.com/rwinlib/gpgme/blob/v1.16.0/include/gpgme.h#L2013-L2015
I also update the version from 2.0.22 to 2.0.23 so that everyone having this issue can update to this latest version to get it fixed. 
Below is the verification result of this PR:
Command to run: `rake compile` 
BEFORE (with the master branch, version 2.0.22): 1 error
AFTER (with the local branch `fix_incompatible_fn_clang16`): …

Fix: incompatible function pointer types with gpgme_op_keylist_ext_start

---

ext/gpgme/extconf.rb

Previously this was not working due to this error:
```
ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:637:in `rm_rf': wrong number of arguments (given 2, expected 1) (ArgumentError)
from extconf.rb:33:in `<main>'
```
Also update the documentation to reflect that --clean is not enabled by default.

Fix --clean option

---

ext/gpgme/extconf.rb

Cleaning is on by default; it's just that prior to #168 the cleaning was quietly failing:
```
Cleaning files only used during build.
/Users/stanhu/.asdf/installs/ruby/3.1.4/lib/ruby/3.1.0/fileutils.rb:637:in `rm_rf': wrong number of arguments (given 2, expected 1) (ArgumentError)
from ./extconf.rb:28:in `block in <main>'
from <internal:dir>:220:in `glob'
from ./extconf.rb:27:in `glob'
from ./extconf.rb:27:in `<main>'
make: [clean-ports] Error 1 (ignored)
```

Revert comment about cleaning not being on by default

---

.gitignore
ext/gpgme/gpgme_n.c
lib/gpgme/ctx.rb
test/ctx_test.rb

This fixes https://github.com/ueno/ruby-gpgme/issues/141.
I added a setter and getter for the `ignore-mdc-error` flag.
- `GPGME::Ctx#ignore_mdc_error`
- `GPGME::Ctx#ignore_mdc_error=`
Example usage:
```rb
ctx = GPGME::Ctx.new
ctx.ignore_mdc_error #=> false
ctx.ignore_mdc_error = true
ctx.ignore_mdc_error #=> true
ctx = GPGME::Ctx.new(ignore_mdc_error: true)
ctx.ignore_mdc_error #=> true
```
I also added a generic pair of getter/setter methods that can be used to set ctx flags that have not been exposed through getters and setters in Ruby.
- `GPGME::Ctx#get_ctx_flag`
- `GPGME::Ctx#set_ctx_flag`
Example usage:
```rb
ctx = GPGME::Ctx.new
ctx.get_ctx_flag("ignore-mdc-error") #=> ""
ctx.ignore_mdc_error = true
ctx.ignore_mdc_error #=> true
ctx.get_ctx_flag("ignore-mdc-error") #=> "1" …
```

Add the `ignore_mdc_error` flag setter and getter

---

ext/gpgme/extconf.rb

When trying to compile this with a current alpine linux, the build fails [because of an upgrade of musl](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.18.0). [musl 1.2.4 removed the LFS64 interfaces](https://musl.libc.org/releases.html), which are used in gpgme. They provide a way to reenable them until sources are updated with `CFLAGS=-D_LARGEFILE64_SOURCE`.
This adds the workaround to the build config until gpgme updates their code.
Here's a stacktrace of the installation without this patch: https://gist.github.com/jk779/33a16851bbe3c6baf7a024eba1fb7dc3
----
See https://github.com/ueno/ruby-gpgme/issues/182

Add workaround for building gpgme with musl >= 1.2.4

---

.github/workflows/test.yml

Add Ruby 3.3 to the CI pipeline matrix to ensure compatibility with this version.

Add Ruby 3.3 to the CI pipeline matrix

---

ext/gpgme/extconf.rb

We had some build failures on macOS with this error:
```
configure: Use gpgrt-config as libassuan-config
checking for LIBASSUAN - version >= 2.4.2... yes (3.0.1)
checking LIBASSUAN API version... does not match.  want=2 got=3.
```
This occurs when:
1. libassuan v3.0 is installed.
2. `PKG_CONFIG_PATH` includes the Homebrew path of `/opt/homebrew/lib/pkgconfig`.
https://github.com/gpg/gpgme/blob/5bf3e6d0754a179b316f90a885371af99bc03ea1/m4/libassuan.m4#L32 attempts to run `gpgrt-config libassuan --exists`. This will return the Homebrew version of libassuan if `PKG_CONFIG_PATH` includes it.
To avoid this build failure, preface `PKG_CONFIG_PATH` with the local versions of libassuan and libgpg-error.

Set PKG_CONFIG_PATH to ensure gpgme builds with local libassuan

---

ext/gpgme/gpgme_n.c
test/data_test.rb

Fixes a few long vs uint comparison warnings, removes one unused variable, and silences a couple ambiguity warnings from the tests.

Fix some warnings

---

.github/workflows/test.yml

Add Ruby 3.4 to the CI pipeline matrix to ensure compatibility with this version.
Tests pass against 3.4 locally.

Add Ruby 3.4 to the CI pipeline matrix
